### PR TITLE
create brief schema, keep pipelineGet as is

### PR DESCRIPTION
**Pull request by bjornaer**
This PR aims to create a Brief schema for PipelineGet  which holds the most basic information for pipelines, this approach was preferred to preserve PipelineGet schema with its original fields, thus avoiding possible unforeseen impact on other services.

### CODE REVIEW

**Review by adamleithp-mystic — DISMISSED** [review]
Looks good to me

**Review by plutopulp — COMMENTED** [review]
Great stuff man! LGTM

**Review by plutopulp — DISMISSED** [review]

**Review by isNeil — DISMISSED** [review]
LGTM!

**Review by isNeil — APPROVED** [review]
LGTM!

**Pull request merged**
